[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDdSrj9QlT_HQjXRP-elkLhLtP5Jx8x8Ug"
  VITE_FIREBASE_AUTH_DOMAIN = "inventory-management-92166.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "inventory-management-92166"
  VITE_FIREBASE_STORAGE_BUCKET = "inventory-management-92166.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "679251672484"
  VITE_FIREBASE_APP_ID = "1:679251672484:web:899117c5ea32c235831531"
  VITE_FIREBASE_MEASUREMENT_ID = "G-17WW0LFQEP"

# Exclude static assets from SPA redirect
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/*.js"
  to = "/:splat.js"
  status = 200

[[redirects]]
  from = "/*.css"
  to = "/:splat.css"
  status = 200

# SPA fallback for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"

[[headers]]
  for = "/__/auth/*"
  [headers.values]
    Cross-Origin-Opener-Policy = "same-origin-allow-popups"
    Cross-Origin-Embedder-Policy = "unsafe-none"