name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      env:
        NODE_ENV: production
        VITE_FIREBASE_API_KEY: AIzaSyDdSrj9QlT_HQjXRP-elkLhLtP5Jx8x8Ug
        VITE_FIREBASE_AUTH_DOMAIN: inventory-management-92166.firebaseapp.com
        VITE_FIREBASE_PROJECT_ID: inventory-management-92166
        VITE_FIREBASE_STORAGE_BUCKET: inventory-management-92166.firebasestorage.app
        VITE_FIREBASE_MESSAGING_SENDER_ID: 679251672484
        VITE_FIREBASE_APP_ID: 1:679251672484:web:899117c5ea32c235831531
        VITE_FIREBASE_MEASUREMENT_ID: G-17WW0LFQEP
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: false